name: Deploy Vulnerable Application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Run docker image
        run:  |
          docker pull bkimminich/juice-shop 
          docker run --rm -p 127.0.0.1:3000:3000 bkimminich/juice-shop
          docker ps
          ifconfig

